spring.application.name=Local-Service-Finder
server.port=8080

#mysql Database configuration
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/finder
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# --- Email Server Configuration (Example: Gmail) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=djgurjar88@gmail.com
spring.mail.password=pbek ckop smqa kkgu

# --- SMTP Properties ---
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=5000

# --- Application Specific (Sender Name) ---
app.email.from=no-reply@finder-app.com

# Admin Email (The recipient of the verification requests)
app.admin.email=dheeraj@mailinator.com
# Base URL of your backend
app.backend.url=http://localhost:8080
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG